.\adb.exe shell pm disable-user --user 0 com.samsung.android.bixby.service
.\adb.exe shell pm disable-user --user 0 com.samsung.android.bixby.agent
.\adb.exe shell pm disable-user --user 0 com.samsung.android.bixby.wakeup
.\adb.exe shell pm disable-user --user 0 com.samsung.android.app.spage
.\adb.exe shell pm disable-user --user 0 com.samsung.android.bixby.agent.dummy
.\adb.exe shell pm disable-user --user 0 com.samsung.android.visionintelligence
.\adb.exe shell pm disable-user --user 0 flipboard.boxer.app
.\adb.exe shell pm disable-user --user 0 com.samsung.android.app.sbrowseredge
.\adb.exe shell pm disable-user --user 0 com.samsung.android.app.taskedge
.\adb.exe shell pm disable-user --user 0 com.samsung.android.app.appsedge
.\adb.exe shell pm disable-user --user 0 com.samsung.android.app.clipboardedge
.\adb.exe shell pm disable-user --user 0 com.samsung.android.game.gamehome
.\adb.exe shell pm disable-user --user 0 com.samsung.android.game.gametools
.\adb.exe shell pm disable-user --user 0 com.samsung.android.scloud
.\adb.exe shell pm disable-user --user 0 com.sec.android.app.samsungapps
.\adb.exe shell pm disable-user --user 0 com.sec.android.widgetapp.samsungapps
.\adb.exe shell pm disable-user --user 0 com.samsung.android.drivelink.stub
.\adb.exe shell pm disable-user --user 0 com.samsung.android.service.peoplestripesamsungpassautofill
.\adb.exe shell pm disable-user --user 0 com.samsung.android.email.provider
.\adb.exe shell pm disable-user --user 0 com.samsung.andorid.fmm
.\adb.exe shell pm disable-user --user 0 com.samsung.android.visionarapps
.\adb.exe shell pm disable-user --user 0 com.mygalaxy
.\adb.exe shell pm disable-user --user 0 com.samsung.android.arzone
.\adb.exe shell pm disable-user --user 0 com.samsung.android.calendar
.\adb.exe shell pm disable-user --user 0 com.samsung.android.app.reminder
.\adb.exe shell pm disable-user --user 0 com.samsung.android.app.simplesharing
.\adb.exe shell pm disable-user --user 0 com.samsung.android.app.tips
.\adb.exe shell pm disable-user --user 0 com.facebook.katana
.\adb.exe shell pm disable-user --user 0 com.facebook.system
.\adb.exe shell pm disable-user --user 0 com.facebook.appmanager
.\adb.exe shell pm disable-user --user 0 com.facebook.services
.\adb.exe shell pm disable-user --user 0 com.linkedin.android
.\adb.exe shell pm disable-user --user 0 com.android.stk2
.\adb.exe shell pm disable-user --user 0 com.samsung.android.svoiceime
.\adb.exe shell pm disable-user --user 0 com.samsung.android.honeyboard
.\adb.exe shell pm disable-user --user 0 com.samsung.android.mdx
.\adb.exe shell pm disable-user --user 0 com.microsoft.appmanager
.\adb.exe shell pm disable-user --user 0 com.microsoft.skydrive
.\adb.exe shell pm disable-user --user 0 com.google.android.apps.googleassistant
.\adb.exe shell pm disable-user --user 0 com.google.android.apps.docs
.\adb.exe shell pm disable-user --user 0 com.google.android.gm
.\adb.exe shell pm disable-user --user 0 com.google.android.googlequicksearchbox
.\adb.exe shell pm disable-user --user 0 com.google.android.youtube